title: Your Site Title
description: Your site description
domain: ahmed1.live
url: "https://ahmed1.live"
baseurl: ""

# Build settings
markdown: kramdown
remote_theme: pages-themes/minimal@v0.2.0  # or any other theme you want to use
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag

# Exclude files from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

