# The Site Configuration

# Import the theme
theme: jekyll-theme-chirpy
remote_theme: cotes2020/jekyll-theme-chirpy@v6.2.3

# Base settings
baseurl: ""
url: "https://ahmed86-star.github.io"
lang: en
timezone: America/New_York

# Site title and branding
title: "Ahmed's Security Lab"
tagline: "Exploring Cybersecurity & Cloud Defense"
description: >-
  🛡️ Security Operations Expert | ☁️ Cloud Security Specialist
  Sharing cutting-edge security research, hands-on labs, and 
  real-world defense strategies in cybersecurity.

# Build settings
markdown: kramdown
permalink: /:categories/:title/

# Plugin settings
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-seo-tag
  - jemoji
  - jekyll-remote-theme
  - jekyll-include-cache

# Disable problematic plugins temporarily
# - jekyll-archives
# - jekyll-redirect-from

# Pagination
paginate: 8
paginate_path: /page:num/

# Collections (simplified)
collections:
  tabs:
    output: true
    sort_by: order

# Exclude list
exclude:
  - .sass-cache
  - .jekyll-cache
  - gemfiles
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - categories
  - assets/feed.xml
  - "*.gem"
  - "*.gemspec"

# Compression settings
sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

# Feed settings
feed:
  path: feed.xml
  posts_limit: 20
  disable_in_development: true

# Layouts
layouts_dir: _layouts

